### PR TITLE
iPhone5s 10.3.1 offsets

### PR DESCRIPTION
**Pull request by d0ppl3r**

### CODE REVIEW

**Comment by d0ppl3r** [comment]
Worked for me when I used initial commit with iPhone8,1 offsets's replacement.

**Comment by arx8x** [comment]
Replacement? and iPhone 8,1? Isn't this for 5s?

**Comment by d0ppl3r** [comment]
Whops.. Sorry for bad english.
Wanted to say: just replaced yours iphone8,1 offsets by mine iPhone6,2 offsets and got v0rtexnonce worked.

**Comment by arx8x** [comment]
You mean, it doesn't load the offsets based on kernel version?
You had to replace iPhone 6s offsets to make it work?
When you run it, is the test offset displayed in xcode console = the x0x0x10 offset of your device?

**Comment by d0ppl3r** [comment]
Yes,I had to replace 6s offsets to make it work,but I didn't get the test offset in xcode console because I just compiled an IPA using 'Archive',but now this IPA is deleted

**Comment by arx8x** [comment]
So it doesn't load the offsets for current device? Are you sure? It may take a lot of tries often

About the console,
I mean, compile this version and watch xcode console. Check if it loads the right x0x0x10 offset

**Comment by d0ppl3r** [comment]
Will compile it soon. Leave this PR opened. If it loads the right offset,I'll notify you. If it doesn't,I'll close PR.

**Comment by arx8x** [comment]
Thanks

**Comment by d0ppl3r** [comment]
Yeah,this offset is an x0x0x10 offset for my device. But I'll check these offsets again using an IPSW.

**Comment by arx8x** [comment]
Great

**Pull request merged**
