### PR TITLE
iPhone 6 10.3.1 offsets

### PR DESCRIPTION
**Pull request by sickmz**

### CODE REVIEW

**Comment by arx8x** [comment]
Is the vtable offset right?

**Comment by sickmz** [comment]
0x6eed188+130

**Comment by d0ppl3r** [comment]
Actually,I recommend you to leave this PR opened.

**Comment by arx8x** [comment]
I just realized it's unreliable to use kernel version string to identify fw+device combination. Compare iPhone 6s , 6s plus and SE 10.3.3 offsets and kernel version strings for example. Kernel version strings match but offsets aren't the same. What I'm gonna do is accept the pull requests after verifying offsets and push my commit that identifies fw+device combinations using build ids and device ids.

**Pull request merged**
